added deprovision job

diff --git a/.github/workflows/deploy_platform.yml b/.github/workflows/deploy_platform.yml
--- a/.github/workflows/deploy_platform.yml
+++ b/.github/workflows/deploy_platform.yml
@@ -50,6 +50,12 @@ on:
         type: boolean
         default: true
 
+      deprovision_after:
+        description: Deprovision after deployment
+        required: true
+        type: boolean
+        default: true
+
 env:
   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   AZURE_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_DEPLOYPLATFORM_AZURE_CLIENT_ID }}
@@ -83,6 +89,7 @@ jobs:
     needs: Setup_Environment
     outputs:
       internal_ip_addr: ${{ steps.deploy_step.outputs.INTERNAL_IP_ADDR }}
+      deployment_id: ${{ steps.deploy_step.outputs.DEPLOY_ID }}
     steps:
       - name: Condition 1 Development
         if: ${{ github.event.inputs.subscription == 'Development' }}
@@ -96,16 +103,24 @@ jobs:
           pwd
           ls -l
           if ${{ github.event.inputs.preload_dataset == 'true' }}; then
-            exec 5>&1
-            DEPLOY_OUTPUT=$(sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} | tee >(cat - >&5))
-            INTERNAL_ADDR_API_SERVICE=$(echo "${{ env.DEPLOY_OUTPUT }}" | grep  "SAIL API Services is hosted internally on: https://172" | cut -f3  -d "/" | tee >(cat - >&5))
-            echo "INTERNAL_IP_ADDR=${{ env.INTERNAL_ADDR_API_SERVICE }}" >> $GITHUB_OUTPUT
-            echo "Internal: ${{ env.INTERNAL_ADDR_API_SERVICE }}"
+            git config --global --add safe.directory '*'
+            git submodule update
+            make clean
+            make all
+            tmp_file="$(mktemp /tmp/deploy_output.XXXXXXXXXX)" || { echo "Failed to create temp file"; exit 1; }
+            trap "rm -f $tmp_file" EXIT
+            sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} | tee $tmp_file
+            internal_addr_api_service = grep -oP "SAIL API Services is hosted internally on: https://.{0,12}" $tmp_file
+            deploy_id = grep -oP "Deployment ID: CI_RUNNER-.{0,36}" $tmp_file
+            echo "INTERNAL_IP_ADDR=${internal_addr_api_service}" >> $GITHUB_OUTPUT
+            echo "DEPLOY_ID=${deploy_id}" >> $GITHUB_OUTPUT
+            echo "Internal: ${internal_addr_api_service}"
+            echo "Deploy ID: ${deploy_id}"
             cd DatasetTool/
             dotnet build
             dotnet publish -c Release
-            bin/Release/net6.0/linux-x64/publish/DatasetTool --email lbart@igr.com --password SailPassword@123 --config SampleData/igr_config.json --ip ${{ env.INTERNAL_ADDR_API_SERVICE }}"
-            bin/Release/net6.0/linux-x64/publish/DatasetTool --email nadams@mghl.com --password SailPassword@123 --config SampleData/mghl_config.json --ip ${{ env.INTERNAL_ADDR_API_SERVICE }}"
+            bin/Release/net6.0/linux-x64/publish/DatasetTool --email lbart@igr.com --password SailPassword@123 --config SampleData/igr_config.json --ip $internal_addr_api_service
+            bin/Release/net6.0/linux-x64/publish/DatasetTool --email nadams@mghl.com --password SailPassword@123 --config SampleData/mghl_config.json --ip $internal_addr_api_service
           else
             git config --global --add safe.directory '*'
             git submodule update
@@ -115,8 +130,11 @@ jobs:
             trap "rm -f $tmp_file" EXIT
             sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} | tee $tmp_file
             internal_addr_api_service = grep -oP "SAIL API Services is hosted internally on: https://.{0,12}" $tmp_file
-            echo "INTERNAL_IP_ADDR=$internal_addr_api_service" >> $GITHUB_OUTPUT
-            echo "Internal: $internal_addr_api_service"
+            deploy_id = grep -oP "Deployment ID: CI_RUNNER-.{0,36}" $tmp_file
+            echo "INTERNAL_IP_ADDR=${internal_addr_api_service}" >> $GITHUB_OUTPUT
+            echo "DEPLOY_ID=${deploy_id}" >> $GITHUB_OUTPUT
+            echo "Internal: ${internal_addr_api_service}"
+            echo "Deploy ID: ${deploy_id}"
           fi
 
       - name: Condition 2 Release Candidate
@@ -168,7 +186,7 @@ jobs:
           fi
 
 
-  test:
+  Test:
     runs-on: [self-hosted, Linux, x64, docker]
     needs: Deploy_Platform
     steps:
@@ -189,3 +207,20 @@ jobs:
             echo "Test Internal IP: ${{ needs.Deploy_Platform.outputs.internal_ip_addr }}"
             echo "No Tests Executed."
           fi
+
+      
+  Deprovision_Platform:
+    runs-on: [self-hosted, Linux, x64, docker]
+    needs: Deploy_Platform
+    steps:
+      - name: Deprovision
+        if: ${{ github.event.inputs.deprovision_after == 'true' }}
+        run: |
+          echo "Deprovision: ${{ github.event.inputs.run_tests }}"
+          echo "Head Ref: ${{ github.head_ref }}"
+          echo "Workspace: ${{ github.workspace }}"
+          sudo chown -R $USER:$USER ${{ github.workspace }}
+          set -e
+          pwd
+          echo "Deployment ID to deprovision: ${{ needs.Deploy_Platform.outputs.deployment_id }}"
+          printf '3\n2\ny\n' | ./Deprovision.sh -o CI_RUNNER
