parse deploy for ip

diff --git a/.github/workflows/deploy_platform.yml b/.github/workflows/deploy_platform.yml
--- a/.github/workflows/deploy_platform.yml
+++ b/.github/workflows/deploy_platform.yml
@@ -97,8 +97,8 @@ jobs:
           ls -l
           if ${{ github.event.inputs.preload_dataset == 'true' }}; then
             exec 5>&1
-            DEPLOY_OUTPUT=$(sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} |tee >(cat - >&5))
-            INTERNAL_ADDR_API_SERVICE=$(echo "${{ env.DEPLOY_OUTPUT }}" | grep  "SAIL API Services is hosted internally on: https://172" | cut -f3  -d "/" |tee >(cat - >&5))
+            DEPLOY_OUTPUT=$(sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} | tee >(cat - >&5))
+            INTERNAL_ADDR_API_SERVICE=$(echo "${{ env.DEPLOY_OUTPUT }}" | grep  "SAIL API Services is hosted internally on: https://172" | cut -f3  -d "/" | tee >(cat - >&5))
             echo "INTERNAL_IP_ADDR=${{ env.INTERNAL_ADDR_API_SERVICE }}" >> $GITHUB_OUTPUT
             echo "Internal: ${{ env.INTERNAL_ADDR_API_SERVICE }}"
             cd DatasetTool/
@@ -107,11 +107,16 @@ jobs:
             bin/Release/net6.0/linux-x64/publish/DatasetTool --email lbart@igr.com --password SailPassword@123 --config SampleData/igr_config.json --ip ${{ env.INTERNAL_ADDR_API_SERVICE }}"
             bin/Release/net6.0/linux-x64/publish/DatasetTool --email nadams@mghl.com --password SailPassword@123 --config SampleData/mghl_config.json --ip ${{ env.INTERNAL_ADDR_API_SERVICE }}"
           else
-            exec 5>&1
-            DEPLOY_OUTPUT=$(sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} |tee >(cat - >&5))
-            INTERNAL_ADDR_API_SERVICE=$(echo "${{ env.DEPLOY_OUTPUT }}" | grep  "SAIL API Services is hosted internally on: https://172" | cut -f3  -d "/" |tee >(cat - >&5))
-            echo "INTERNAL_IP_ADDR=${{ env.INTERNAL_ADDR_API_SERVICE }}" >> $GITHUB_OUTPUT
-            echo "Internal: ${{ env.INTERNAL_ADDR_API_SERVICE }}"
+            git config --global --add safe.directory '*'
+            git submodule update
+            make clean
+            make all
+            tmp_file="$(mktemp /tmp/deploy_output.XXXXXXXXXX)" || { echo "Failed to create temp file"; exit 1; }
+            trap "rm -f $tmp_file" EXIT
+            sudo -E ./DeployPlatform.sh -p ${{ github.event.inputs.purpose }} -o ${{ github.event.inputs.owner }} | tee $tmp_file
+            internal_addr_api_service = grep -oP "SAIL API Services is hosted internally on: https://.{0,12}" $tmp_file
+            echo "INTERNAL_IP_ADDR=$internal_addr_api_service" >> $GITHUB_OUTPUT
+            echo "Internal: $internal_addr_api_service"
           fi
 
       - name: Condition 2 Release Candidate
